### ISSUE TITLE
[Errno 13] Permission denied - inotify

### ISSUE THREAD

**Issue by dooniem** [racklin/simple-synoindex-server#8]
Hi, I somehow need to set different permissions for my inotify?
Could you please help me do that?

I also tried installing on Python 2.7. Same error

2021-05-23 19:31:23,393 ERROR An uncaught exception occurred
Traceback (most recent call last):
  File "/var/packages/py3k/target/usr/local/lib/python3.8/site-packages/synoindexwatcher/__main__.py", line 218, in <module>
    start()
  File "/var/packages/py3k/target/usr/local/lib/python3.8/site-packages/synoindexwatcher/__main__.py", line 188, in start
    inotify.add_watch_recursive(path, mask, filter)
  File "/var/packages/py3k/target/usr/local/lib/python3.8/site-packages/inotifyrecursive/inotifyrecursive.py", line 116, in add_watch_recursive
    return self.__add_watch_recursive(path, mask, filter, name, -1, False)
  File "/var/packages/py3k/target/usr/local/lib/python3.8/site-packages/inotifyrecursive/inotifyrecursive.py", line 79, in __add_watch_recursive
    wd = inotify_simple.INotify.add_watch(self, path, mask | flags.IGNORED | flags.CREATE | flags.MOVED_FROM | flags.MOVED_TO)
  File "/var/services/homes/<USR>/.local/lib/python3.8/site-packages/inotify_simple.py", line 105, in add_watch
    return _libc_call(_libc.inotify_add_watch, self.fileno(), fsencode(path), mask)
  File "/var/services/homes/<USR>/.local/lib/python3.8/site-packages/inotify_simple.py", line 38, in _libc_call
    raise OSError(errno, strerror(errno))
PermissionError: [Errno 13] Permission denied

**Comment by dooniem** [comment]
Bah, I manged to figure it out. Lots of re-install and manual deletion.
